### ISSUE TITLE
Expect true and false to be excluded from ValidIdentifier

### ISSUE THREAD

**Issue by jakesee** [Bunny83/LSystem#1]
There is a bug where the true and false will not be parsed correctly as it will be treated as an expression variable instead.

Solution: Add true and false to the exclusion list.

```
private static bool ValidIdentifier(string aExpression)
{
    aExpression = aExpression.Trim();
    if (string.IsNullOrEmpty(aExpression))
        return false;
    if (aExpression.Length < 1)
        return false;
    if (aExpression.Contains(" "))
        return false;
    if(aExpression == "true" || aExpression == "false")
        return false;
    char firstLetter = char.ToLower(aExpression[0]);
    if (firstLetter != '_' && (firstLetter < 'a' || firstLetter > 'z'))
        return false;
    return true;
}
```

**Comment by Bunny83** [comment]
I agree that there is a rare case where this is possible. However only if you use true or false in a numeric expression. Since implicit conversion is supported I'll add those two exceptions. Thanks for the report :)
1819dc8
